name: Craftensions
version: ${project.version}
main: net.craftions.craftensions.Craftensions
api-version: 1.16
commands:
  extension:
    usage: /<command> <list|remove|install|update> [<type>:<name>]
    permission: craftensions.command.extension
    aliases:
      - ex
      - exmgr
      - extensionmgr