name: Craftensions
version: ${project.version}
main: net.craftions.craftensions.Craftensions
api-version: 1.13
commands:
  extension:
    usage: /<command> <remove|install> <name>
    permission: craftensions.command.extension
    aliases:
      - ex
      - exmgr
      - extensionmgr