name: FancyCommands
version: ${project.version}
main: net.craftions.fancycommands.FancyCommands
api-version: 1.13
authors: [ MCTzOCK ]
depend:
  - Vault
  - Craftensions
commands:
  gamemode:
    usage: /<command> <mode>
    permission: fancycommands.gamemode
    aliases:
      - gm
  gmc:
    usage: /<command>
    permission: fancycommands.gamemode
  gms:
    usage: /<command>
    permission: fancycommands.gamemode
  gma:
    usage: /<command>
    permission: fancycommands.gamemode
  gmsp:
    usage: /<command>
    permission: fancycommands.gamemode
  heal:
    usage: /<command> [player]
    permission: fancycommands.heal
  weather:
    usage: /<command> <sun|rain|thunder> [world]
    permission: fancycommands.weather
  sun:
    usage: /<command> [world]
    permission: fancycommands.weather
  rain:
    usage: /<command> [world]
    permission: fancycommands.weather